import type { Metadata } from "next";
import { Providers } from './uiProvider';
import { Zen_Kaku_Gothic_New } from 'next/font/google';
import "./globals.css";

import { Header } from '../components/elements/header'
import { Footer } from '../components/elements/footer'

const ZenKakuGothicNew = Zen_Kaku_Gothic_New({
  display: 'swap',
  weight: ['300', '400', '500', '700', '900'],
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={ZenKakuGothicNew.className}>
      <Providers><Header></Header></Providers>
      {children}
      <Providers><Footer></Footer></Providers>
      </body>
    </html>
  );
}
